version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./database/create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh
    env_file:
      - .env

  backend:
    build:
      context: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery_worker:
    build:
      context: .
    command: celery -A celery_app.worker worker --loglevel=info
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  tests:
    build:
      context: .
    command: pytest -s -v
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - backend
      - postgres
      - redis

volumes:
  postgres-data:
    driver: local
