"""empty message

Revision ID: 48d137b96a64
Revises: 09809c0a5a42
Create Date: 2024-07-04 22:40:37.598903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48d137b96a64"
down_revision: Union[str, None] = "09809c0a5a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("is_blocked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "is_blocked")
    # ### end Alembic commands ###
